# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaus_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_model',
        ),
    ]
