# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomHashes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=10)),
            ],
        ),
    ]
