# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_shorturl_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='visists',
            field=models.IntegerField(default=0),
        ),
    ]
