# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_shorturl_visists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='visists',
            new_name='visits',
        ),
    ]
